spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_jpa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '12341234' #PC 1234 , 노트북 12341234

  jpa:
    hibernate:
      ddl-auto: create #생성할떄마다 초기화
    properties:
      hibernate:
        format_sql: true
#       show_sql :true #콘솔에 남기는 방식
logging:
  level:
    org:
      hibernate:
        SQL: debug #로그

